### ISSUE TITLE
Chaotic Attractor Replication

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/NeuralNetDiffEq.jl#34]
https://arxiv.org/pdf/1710.07313.pdf

**Comment by MartinuzziFrancesco** [comment]
I've been working on an implementation of the code for this paper: https://github.com/MartinuzziFrancesco/EchoStateNetwork  

The results are a little inconsistent, I don't know yet if it is because of my implementation or is an inherent problem of the model. Or maybe even the parameters given by the paper are not the best. This is something to work on. I am only using the Lorenz system as benchmark for the moment and I still have to calculate the Lyapunov exponents.

After the actual conclusion of the implementation of the model there are a few interesting directions in which one can go that I expressed in the readme on the repository: 
- the study of the differences between the non linear transformation algorithms
- the implementation of different systems in the reservoir. 

If you have any suggestions or corrections I am more than happy to listen to them.

**Comment by ChrisRackauckas** [comment]
Interesting. Can you show what the plots look like in phase space? IIRC, it should get the attractor correct though not the trajectories.

**Comment by MartinuzziFrancesco** [comment]
Of course, I just added an image to the repo: https://github.com/MartinuzziFrancesco/EchoStateNetwork/blob/master/attractor_com.png

**Comment by ChrisRackauckas** [comment]
oh that's looking pretty good. Are you looking to turn this into package code?

**Comment by MartinuzziFrancesco** [comment]
Yes, the intention was to finish the details around the model and then work towards turning it into a package code. 
Besides the points I have expressed in the first message, do you have any other idea in particular to which direction to go regarding this model?

**Comment by ChrisRackauckas** [comment]
>Besides the points I have expressed in the first message, do you have any other idea in particular to which direction to go regarding this model?

I think it's fine where it is, for now. I think making it have a package interface so that it would be easy to try other models is where to go, since then it would be be easier to test in a larger context of models.

**Comment by MartinuzziFrancesco** [comment]
Wonderful, I will start working on that in these days. With the last changes in the code the results are actually very consistent and in line with those given by the paper, yielding good short term predictions and a similar attractor. If you want to take a look I have updated the pictures in the repo.

**Comment by MartinuzziFrancesco** [comment]
All packaged up, just waiting on the JuliaRegistrator. I've made a few changes in the meantime so the code is cleaner to use but there is still a lot of room for improvements of course.
